### ISSUE TITLE
Extending page when launching webcam multiple times

### ISSUE THREAD

**Issue by JoeHolt** [stsievert/next-face-demo#6]
When launching the webcam multiple times in one session, the page expands downwards when it should not.

**Comment by stsievert** [comment]
This is closed, right @JoeHolt? You mentioned it in conversation today.

**Comment by JoeHolt** [comment]
Yes, this bug has been corrected.

**Comment by stsievert** [comment]
> Yes, this bug has been corrected

Or: that bug has been squashed!
